services:
  postgres:
    image: 'postgres:16'
    container_name: barberia-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql.prod:/docker-entrypoint-initdb.d/init-databases.sql:ro
    networks:
      - barberia-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - barberia-net

  identity-service:
    build: ./identity-service
    container_name: identity-service
    environment:
      - EUREKA_URL=${EUREKA_URL}
      - DB_IDENTITY_URL=${DB_IDENTITY_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - barberia-net

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    environment:
      - EUREKA_URL=${EUREKA_URL}
      - DB_CATALOG_URL=${DB_CATALOG_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - eureka-server
    networks:
      - barberia-net

  organization-service:
    build: ./organization-service
    container_name: organization-service
    environment:
      - EUREKA_URL=${EUREKA_URL}
      - DB_ORGANIZATION_URL=${DB_ORGANIZATION_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - eureka-server
    networks:
      - barberia-net

  booking-service:
    build: ./booking-service
    container_name: booking-service
    environment:
      - EUREKA_URL=${EUREKA_URL}
      - DB_BOOKING_URL=${DB_BOOKING_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - eureka-server
    networks:
      - barberia-net

  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=${EUREKA_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - eureka-server
    networks:
      - barberia-net

networks:
  barberia-net:
    driver: bridge

volumes:
  postgres_data: